language: c
dist: trusty
sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mlton libgmp-dev

env:
  global:
    - MAKEFLAGS="-j 2"

branches:
  only:
  - master

script: make && make test
